### ISSUE TITLE
React rewrite 

### ISSUE THREAD

**Issue by jmviz** [jmviz/wety-client#1]

**Comment by DonMiller9294** [comment]
Hello could you give a description of the issue?

**Comment by jmviz** [comment]
Hi. I have been working on a version of the frontend that uses react and mui for various components here [jmviz/wety/tree/client](https://github.com/jmviz/wety/tree/client). Once I have finished reproducing the current functionality, I plan to shift the github pages deployment to that repository and archive this one.
